import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const pessoas = api.profile.getAllUsers.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ff0000] to-[#f4ab4c]">
        {status !== "authenticated" ? (
          <button
            className=" rounded border-2 border-gray-200 py-4 px-8 text-lg font-bold shadow-2xl"
            onClick={() => signIn()}
          >
            Login
          </button>
        ) : (
          <div>logado</div>
        )}

        <div className="flex flex-col items-center justify-center">
          {pessoas.data?.map((pessoa) => (
            <div key={pessoa.id}>{pessoa.id}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
